config/routes.rb
Rails.application.routes.draw do
  get 'feed', to: "epicenter#feed"
  get 'show_user', to: "epicenter#show_user"
  get 'now_following', to: "epicenter#now_following"
  get 'unfollow', to: "epicenter#unfollow"  
  get 'tag_tweets', to: "epicenter#tag_tweets"
  get 'all_users', to: "epicenter#all_users"
  # THis is going to show all the user followers 
  get 'followers', to: "epicenter#followers"
  get "followings", to: "epicenter#followings"
  
  #This associates a tweet with the comments 
  resources :tweets do 
    resources :comments
  end

  devise_for :users
  root 'epicenter#feed'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  require 'will_paginate/array'

  def feed
    #This include tweeets from people we follow and our own tweets 
    @following_tweet = []
    @tweets = Tweet.order('created_at DESC')
    @tweets.each do |tweet| 
      if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id 
        @following_tweet.push(tweet)
      end
    end
    #For pagination
    @following_tweet = @following_tweet.paginate(page: params[:page], per_page: 10)
    @comment = Comment.new 
  end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    #You have to push as an integer because on the show_user page it is searching for if the current_user includes? (@user.id)
    #@ user.id is an integer 
    current_user.following.push(params[:id].to_i) #This is yourself 
    current_user.save
    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save 
    redirect_to show_user_path(id: params[:id])
  end


  def tag_tweets
    @tag = Tag.find(params[:tag_id])
  end

  def all_users
    @users = User.all
  end
  
  #Followers are going to show the followers of a certain user 
  #That user is going to be called @user 
  #We are trying to iterate through all the users and is if they have @user.id in their following array  
  def followers 
    @user = User.find(params[:id])
    @users = []
    User.all.each do |person| 
      if person.following.include?(@user.id)
        @users.push(person)
      end
    end
  end

  #Followings are going to show us the followings of a certain user 
  # @user is the owner of the page 
  #What we are trying to do is iterate through each user and check if our main @user has their id inside our following array 
  def followings 
    @user = User.find(params[:id])
    @users = []
    #I want to check if @user following array has the person id in it 
    #If the person's id is in @user.following than that person must be following @user
    User.all.each do |person| 
      #If this is true we want to push it into @users to iterate through it in the view page 
      if @user.following.include?(person.id)
        @users.push(person)
      end
    end
  end


end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/views/epicenter/_user_list.html.erb
<% @users.each do |user| %>
    <div class="jumbotron" style="min-height: 200px;">
        <div class="row">
            <div class="col-md-4">
                <% if !user.avatar.blank? %>
                    <%# If the user does NOT have an avatar %>
                    <%=link_to image_tag(user.avatar.url, class: "avatar-size"), show_user_path(id: user.id)  %>
                <% else %>
                    <%# If the user does have an avatar %> 
                    <%= link_to image_tag('gravatar.jpg', class: "avatar-size"), show_user_path(id: user.id) %>
                <% end %>
            </div>
            <div class="col-md-8">
                <%=link_to show_user_path(id: user.id) do %>
                    <h2>@<%= user.username %></h2>
                    <p> <%= user.name.capitalize %></p>
                <% end %>
                <%# if I am  following that person,  show a link to unfollow %>
                <% if current_user.following.include?(user.id) %>
                    <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id:"unfollow_btn" %>
                <% elsif current_user.id != user.id %>
                    <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
                <hr>
                <p>
                    Bio: <%= user.bio %>                    
                </p>
            </div>
        </div><!-- end of -->
    </div>
<% end %>

app/views/epicenter/all_users.html.erb
<center>
    <h1>All Users</h1>
</center>

<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<h1>My Feed</h1>
<% @following_tweet.each do |tweet| %>
    <div class="jumbotron">
        <%=link_to tweet.user.username, show_user_path(id: tweet.user_id)  %>| <%= tweet.message.html_safe %>
        <%# Show this customize message when tweet was created less then a day %>
        - <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
        <%# if tweet was created more than a day we will format it with the Month and day %>
        <%= tweet.created_at.strftime('Created on %b %e') if  Time.now - tweet.created_at > 86400%>

        <% tweet.comments.each do |c| %>
            <div class="panel panel-default">
                <div class="panel-body">
                    <%= c.post %>
                    - <%= link_to  "@#{c.user.username}", show_user_path(id: c.user_id)  %>
                    <br>
                    <%= c.created_at.strftime('%b %e')%>

                </div>
            </div>
        <% end %>
        <!-- This is a form for comments -->
        <%= form_for([tweet, @comment ]) do |f| %>
            <%= f.text_field :post, class: "form-control", placeholder: "Comment" %>
            <%= f.hidden_field :tweet_id, :value => tweet.id%>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit %>
        <% end %>
    </div>
<% end %>



<%= will_paginate @following_tweet %>

app/views/epicenter/followers.html.erb
<h1>Followers</h1>
<%= render 'user_list' %>

app/views/epicenter/followings.html.erb
<h1> <%= link_to "@#{@user.username.capitalize}'s Followings", show_user_path(id: @user.id) %> </h1>

<%= render 'user_list' %> 

app/views/epicenter/show_user.html.erb
<h1>@<%=@user.username%>'s Profile</h1>
<%= link_to "Followers", followers_path(id: @user.id)%> | 
<%= link_to "Followings", followings_path(id: @user.id) %>

<p>Bio: <%=@user.bio %></p>
<p>Location: <%=@user.location %></p>
<p>
    <% if current_user.following.include?(@user.id) %>
        <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id:"unfollow_btn" %>
    <% elsif current_user.id != @user.id %>
        <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
    <% end %>
</p>


<% @user.tweets.each do |tweet| %>
    <div class="jumbotron">
        <%= tweet.message %>- <%=time_ago_in_words(tweet.created_at) %>
    </div>

<% end %>


<%= link_to "Back to Feed", feed_path, class: "btn btn-link"%>

app/views/epicenter/tag_tweets.html.erb
<div>
    <h1>
        <%= @tag.phrase %>
    </h1>
</div>
<hr>


<div class="row">
    <% @tag.tweets.order(created_at: :desc).each do |tweet|  %>
    <div class="jumbotron">
        <p>
            <%= "@#{tweet.user.username} "%> - <%= time_ago_in_words(tweet.created_at)%> <hr>
            <%= tweet.message.html_safe %>
        </p>
     </div>   
    <% end %>
</div>