config/routes.rb
Rails.application.routes.draw do
  get 'feed', to: "epicenter#feed"
  get 'show_user', to: "epicenter#show_user"
  get 'now_following', to: "epicenter#now_following"
  get 'unfollow', to: "epicenter#unfollow"  
  get 'tag_tweets', to: "epicenter#tag_tweets"
  get 'all_users', to: "epicenter#all_users"
  # THis is going to show all the user followers 
  get 'followers', to: "epicenter#followers"
  get "followings", to: "epicenter#followings"
  
  #This associates a tweet with the comments 
  resources :tweets do 
    resources :comments
  end

  devise_for :users
  root 'epicenter#feed'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TtsSocial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">TTS Social</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Create a Tweet", new_tweet_path %></li>       
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= all_users_path %>">All Users</a></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if !current_user.avatar.blank?%>
              <%= image_tag(current_user.avatar.url, size: "25x25") %>
            <% end %>
            @<%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile",edit_user_registration_path %> </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
            </ul>
          </li>
        <% else %>
              <li><%= link_to "Login",  new_user_session_path %> </li>
              <li><%= link_to "Sign Up", new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>





   <div class="container">
      <%= yield %>
    </div> 


  </body>
</html>